### ISSUE TITLE
Upload snapshots in most-recent-first order, check whether target exists just before uploading, add per-snapshot lock files

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/backoid#3]
It is theoretically possible that a snapshot upload will take longer to upload than the time between snapshots are taken, e.g. with hourly snapshots that take more than an hour to upload.

To mitigate the risk of the same snapshots being uploaded over and over again (they are not visible via `rclone ls` until the upload completes), upload the most recent snapshot (last in alphanumeric order) first. Additionally, check that the tarball doesn't already exist just before uploading. This will approximately double the time we have before we start clobbering uploads already in progress for each snapshot.

To fully correct this, we need lock files (similar to what syncoid uses) to prevent the same transfer happening multiple times concurrently.

**Comment by gordan-bobic** [comment]
Oops, I just spotted in the code that we already seem to have locking, so that's good. There is still value in uploading in most-recent-first order, though (it's possible I also missed the part where it already does this).

**Comment by oblitorum** [comment]
No, currently it's not in most-recent-first order, we can use the `-S creation` option of `zfs list`, that will list the snapshot in `creation,DESC` order, and then we deal with it one by one, that should do I think.

**Comment by gordan-bobic** [comment]
Sounds good, that should do it.
