### ISSUE TITLE
Add setting for extra user defined options for compressor and rclone

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/backoid#6]
I think there is value in adding settings for passing additional raw options that can be passed to the compressor or rclone, for example:

```
# to make pzstd compressor fork 24 threads instead of using only one
compressor_options = --threads=24
# to tell rclone use a 32MB buffer instead of default size
rclone_options = --buffer-size=32M
```

**Comment by oblitorum** [comment]
Should we add set these 2 options as default?

**Comment by gordan-bobic** [comment]
No, default should be blank for both of those. It's advanced stuff for people who *really* know what they are doing.

**Comment by oblitorum** [comment]
OK, got it
